version: "3"
services:
  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql
    working_dir: "/app"

  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/favorite_spot
    ports:
      - "8000:8000"